version: "3.3"
services:
  arangobd:
    image: arangodb:3.11.8
    container_name: arangodb
    ports:
      - "8529:8529"
    volumes:
      - /passivedns-data:/var/lib/arangodb3
    environment:
      - ARANGO_ROOT_PASSWORD=
  frontend:
    build: 
      context: ../dev/PassiveDNS/front
      dockerfile: ./docker/prod/Dockerfile
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - api
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
  api:
    image: api:test
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - arangobd
    env_file:
      - ${PASSIVEDNS_DOCKER_ENVFILE}
    entrypoint:
      - /docker-entrypoint.sh
    command: ["webserver"]
  scheduler:
    image: sched:test
    container_name: scheduler
    depends_on:
      - api
      - redis
    env_file:
      - ${PASSIVEDNS_DOCKER_ENVFILE}
    entrypoint:
      - /docker-entrypoint.sh
    command: ["scheduler"]
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /passivedns-data:/data
networks:
  default:
    name: yeti_network
